#Config settings
author:
   name: Genji Noguchi
   email: genji.noguchi@gmail.com
description: hurr
baseurl: 
url: "http://localhost:4000"

#build settings
markdown: kramdown
highlighter: true

collections:
    ventures:
        output: true

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
