# Site Variables
title           : "Genji Home"
name			: "Genji"
description     : "Genji Noguchi's Home Page!"
url             : "localhost:4000"
baseurl         : /
version			: 0.0.1

#Dependencies
markdown        : redcarpet
highlighter     : true

# Blog Settings
paginate		: 5
paginate_path	: /blog/page:num
permalink		: /blog/:year/:month/:day/:title/
excerpt_separator: <!--end_excerpt-->

# Collections
collections:
    portfolio:
        output : true
        permalink : /portfolio/:path/index.html

# Bio
#author:
#	name		: "Genji Noguchi"
#s	url			: "https://linkedin.com/in/genjinoguchi"
