# Site Variables
title           : "Genji Home"
name			: "Genji"
description     : "Genji Noguchi's Home Page!"
url             : "localhost:4000"
baseurl         : /
version			: 2.0.1

#Exclude
exclude         : ['test-project.md', 'test-software.md', 'test-hardware.md']

#Dependencies
markdown        : redcarpet
highlighter     : true

# Blog Settings
paginate		: 5
paginate_path	: /blog/page:num
permalink		: /blog/:year/:month/:day/:title/
excerpt_separator: <!--end_excerpt-->

# Gems
gems : [jekyll-paginate, redcarpet]

# Collections
collections:
    portfolio:
        output : true
        permalink : /portfolio/:path/index.html
    css:
        output : true
        permalink : /res/css/:path.css

# Sass
sass:
    sass_dir : _sass

# Bio
#author:
#	name		: "Genji Noguchi"
#	url			: "https://linkedin.com/in/genjinoguchi"
