#Config settings
name: Genji Noguchi
email: genji.noguchi@gmail.com
description: hurr
baseurl: ""
url: "genjinoguchi.github.io"

#build settings
markdown: kramdown

defaults:
   -
     scope:
       path: ""
       type: "posts"
     values:
       layout: "default"

